.gitignore
.rspec
.rubocop.yml
.travis.yml
Gemfile
LICENSE.txt
README.md
Rakefile
bin/console
bin/pushmi_pullyu
bin/setup
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/version.rb
pushmi_pullyu.gemspec
spec/pushmi_pullyu_spec.rb
spec/spec_helper.rb

Basically a new gem creation (`bundle new <new_gem>`) with some very simple CLI for parsing options and skeleton runner. Also added rubocop and few other things.

Gemify of pushmi_pullyu

---

pushmi_pullyu.gemspec
spec/pushmi_pullyu_spec.rb

In anticipation of hooking up to CI.

Have rubocop and RSpec pass.

---

.rubocop.yml
Rakefile
lib/pushmi_pullyu/cli.rb

Also turned off Style/SymbolArray cop which forces array of symbols to use`%i` or `%I` instead of brackets

Add rubocop to default rake task for travisCI

---

.gitignore
exe/pushmi_pullyu
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/config.rb
lib/pushmi_pullyu/logging.rb
pushmi_pullyu.gemspec
spec/cli_spec.rb
spec/config_spec.rb
spec/logging_spec.rb
spec/pushmi_pullyu_spec.rb
spec/spec_helper.rb

#18 
* Refactor CLI stuff and add some spec tests for it
* Extract default options into a config class
* Setup logger for PushmiPullyu
* Add daemon support using Daemons gem

Specs for CLI class, bunch more refactors and adding daemon functionality

---

.coveralls.yml
README.md
pushmi_pullyu.gemspec
spec/spec_helper.rb

PR for wrapping up #30.
* Adds coveralls/test coverage metrics to CI build
* Also add some nice rspec config with some comments

#30: Add coveralls for CI Build

---

spec/spec_helper.rb

Currently says we got 100% but that isn't correct as it isn't doing the coverage on the gem code. This should fix it.

Quick fix for Coveralls

---

pushmi_pullyu.gemspec
spec/spec_helper.rb
spec/support/vcr.rb

Issue #27, add VCR.

---

spec/pushmi_pullyu/cli_spec.rb

@astrilet review this and pull it into your branch. This will get Rspec passing with current test suite.
TravisCI still fails because of rubocop issues. Make sure you fix thoses as well.

Get Travis working, by mocking connection to swift

---

.editorconfig
README.md

* Updated Readme with some extra stuff. Especially around configuration and how to run pushmi_pullyu.
* Add editorconfig file for consistent editor configs/styles
Markdown rendered version here: https://github.com/murny/pushmi_pullyu/blob/update_readme/README.md

Update README with new sections about config, testing, etc.

---

examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/logging.rb
spec/fixtures/config.yml
spec/pushmi_pullyu/cli_spec.rb
spec/pushmi_pullyu/logging_spec.rb

(also changed logfile flag to logdir so is more useful and can be used to configure location of both logs)
This PR closes #15 issue

Add logging of preservation event to both application and preservation event logs

---

examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/aip.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/logging.rb
spec/fixtures/config.yml
spec/integration/acceptance_spec.rb
spec/pushmi_pullyu/aip_spec.rb
spec/pushmi_pullyu/cli_spec.rb
spec/pushmi_pullyu/logging_spec.rb
spec/pushmi_pullyu/preservation_queue_spec.rb
spec/support/http_cache/vcr/aip_download_and_swift_upload.yml

Integration test

---

README.md
lib/pushmi_pullyu/cli.rb

- Change past tense to present tense
- Update high level process workflow
- Update help options
- Make it obvious config file should be a YAML file

Small updates to readme

---

lib/pushmi_pullyu/version.rb

Bump version

---

lib/pushmi_pullyu/version.rb

Version bump. New release to include bug fix for #77

Bump patch version for bug found in swift code

---

examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/aip/downloader.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/swift_depositer.rb
pushmi_pullyu.gemspec
spec/fixtures/config.yml
spec/pushmi_pullyu/aip/fedora_fetcher_spec.rb
spec/pushmi_pullyu/aip/solr_fetcher_spec.rb
spec/pushmi_pullyu/cli_spec.rb
spec/pushmi_pullyu/swift_depositer_spec.rb

Changes required for keystone authorization v3 to work

Fixes for keystone v3 authorization

---

README.md
lib/pushmi_pullyu/version.rb

bump version and add info to readme on how to release the gem

Update version and add readme info about releasing gem

---

lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/version.rb

Fixing options bug

---

lib/pushmi_pullyu/swift_depositer.rb
lib/pushmi_pullyu/version.rb

when creating new file in swift metadata was missing. fix #105

Fix missing metadata in swift

---

lib/pushmi_pullyu/version.rb

bump the version to 0.2.7

---

lib/pushmi_pullyu/aip/downloader.rb
lib/pushmi_pullyu/cli.rb
pushmi_pullyu.gemspec
spec/pushmi_pullyu/cli_spec.rb

Also making code comply to changes in cops.

Issue #136. Upgrading rubocop

---

lib/pushmi_pullyu/aip.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/logging.rb
spec/integration/acceptance_spec.rb
spec/pushmi_pullyu/logging_spec.rb

Add file details to preservation logs on successful upload

---

lib/pushmi_pullyu/cli.rb

Slapped this together to filter user/password information out of `IOError`s thrown by the RDF gem that were being passed on to Rollbar

Add filtering for sensitive information in errors reported to Rollbar

---

lib/pushmi_pullyu/aip/fedora_fetcher.rb
spec/pushmi_pullyu/cli_spec.rb
spec/spec_helper.rb

Small changes to get the build to pass.

Fix rubocop offenses

---

lib/pushmi_pullyu.rb
lib/pushmi_pullyu/aip/downloader.rb
pushmi_pullyu.gemspec
spec/fixtures/config.yml
spec/integration/acceptance_spec.rb
spec/pushmi_pullyu/aip/downloader_spec.rb
spec/support/http_cache/vcr/aip_download_and_swift_upload.yml
spec/support/http_cache/vcr/aip_downloader_run.yml

Jupiter's AIP API is protected by username/password pairs; pushmi_pullyu
needs to provide identification credentials to be able to access
restricted data.

Add http authentication for Jupiter calls

---

.rubocop.yml
.travis.yml
examples/pushmi_pullyu.yml
lib/pushmi_pullyu/cli.rb
pushmi_pullyu.gemspec

Ruby 2.4 has EOL date of 2020-03-31 so we need to update the minimum
requirements.

Update ruby version to 2.5

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE
.github/workflows/ruby.yml
Dangerfile
README.md
docker-compose-ci.yml

Adding github workflow brings the project in line with Jupiter following the same testing mechanism.
This PR includes files describing the github workflow for CI, a template for PR descriptions, and definition of code owners.

Add github workflow

---

CHANGELOG.md
lib/pushmi_pullyu/version.rb

Prepare for 2.0.2 release
Updated CHANGELOG and version.rb version.

Bump CHANGELOG and VERSION for 2.0.2 release

---

.github/CODEOWNERS
.rubocop.yml
CHANGELOG.md
README.md
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/aip/downloader.rb
pushmi_pullyu.gemspec
spec/integration/acceptance_spec.rb
spec/pushmi_pullyu/aip/creator_spec.rb
spec/pushmi_pullyu/aip/downloader_spec.rb
spec/pushmi_pullyu/aip_spec.rb
spec/pushmi_pullyu/logging_spec.rb
spec/pushmi_pullyu/preservation_queue_spec.rb
spec/pushmi_pullyu_spec.rb
spec/spec_helper.rb

A couple of issues were blocking anything passing CI. I removed coveralls because it doesn't work without modification for Github actions and addressed some rubocop nags.
Related to https://github.com/ualbertalib/pushmi_pullyu/pull/250#discussion_r855626064
- remove coveralls
- rubocop linter nags addressed

Unblock CI

---

CHANGELOG.md

Updates to the changelog with information about recent gem updates from dependabot.

Update CHANGELOG with recent dependabot updates

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

Prepare for 2.0.6 release

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

Simple version bump to cut release.

Prepare version bump 2.1.0

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

Bump version 2.1.2

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

- Refresh authentication token after it expires [#311](https://github.com/ualbertalib/pushmi_pullyu/issues/311)

Release 2.1.3
