.gitignore
.rubocop.yml

(in case the programmer wants to install bundled gems in vendor bundle).

Have git and rubocop ignore 'vendor'

---

pushmi_pullyu.gemspec

Fixes the following warnings:
```
WARNING:  open-ended dependency on activesupport (>= 0) is not recommended
if activesupport is semantically versioned, use:
add_runtime_dependency 'activesupport', '~> 0'
WARNING:  pessimistic dependency on daemons (~> 1.2.4) may be overly strict
if daemons is semantically versioned, use:
add_runtime_dependency 'daemons', '~> 1.2', '>= 1.2.4'
WARNING:  open-ended dependency on redis (>= 0) is not recommended
if redis is semantically versioned, use:
add_runtime_dependency 'redis', '~> 0'
WARNING:  open-ended dependency on connection_pool (>= 0) is not recommended
if connection_pool is semantically versioned, use:
add_runtime_dependency 'connection_pool', '~> 0'
WARNING:  open-ended dependency on bundler (>= 1.14, development) is not recommended
if bundler …
```

Fix gem warnings on open ended or pessimistic dependencies

---

.travis.yml

Since we now use redis, Add redis-server service to travisCI to fix failing builds

Add redis to travicCI build to fix failing builds

---

examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
spec/fixtures/config.yml
spec/fixtures/config_with_envs.yml
spec/pushmi_pullyu/cli_spec.rb

Make queue top level option and fix option setter to be a merge on default options instead of a straight up assignment/override.

#47: Fixes for Handle PMPY configuration via yaml file

---

examples/pushmi_pullyu.yml
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/preservation_queue.rb
pushmi_pullyu.gemspec
spec/fixtures/config.yml
spec/pushmi_pullyu/cli_spec.rb
spec/spec_helper.rb
spec/support/rollbar.rb

Basic reporting of errors to Rollbar. The example run-loop setup will report the error and crash the daemon if an error occurs while retrieving a noid from the queue, or if the noid is retrieved successfully, report any errors that occur in the loop with information about the current noid, but continue on to the next noid. We can tweak this as we like.
Rollbar integration is only active when a token is passed in the options. Rollbar is configured to not pass errors back to the API even with a token configured, if RSpec is running.
I've had to do a localized cop disable to make rubocop happy, but that may indicate that we don't want that cop.
Closes #32

Add basic error reporting to PMPY

---

.rubocop.yml
spec/pushmi_pullyu/cli_spec.rb
spec/pushmi_pullyu/logging_spec.rb
spec/pushmi_pullyu/preservation_queue_spec.rb

Team agreed that it's better to use explicit style instead of described_class style for rspec tests. Changing cop to reflect this.
So from now on use explicit style (PushmiPullyu::ClassName) instead of described_class helper
Updated all specs affected by this as well.

Reverse Rspec/DescribedClass rubocop decision

---

lib/pushmi_pullyu/swift_depositer.rb
spec/pushmi_pullyu/swift_depositer_spec.rb
spec/support/http_cache/vcr/swift_new_deposit.yml

Something we haven't been doing yet.
From according to AIP spec( https://docs.google.com/document/d/154BqhDPAdGW-I9enrqLpBYbhkF9exX9lV3kMaijuwPg/edit) we need to add metadata when we upload our deposited files in Swift:
```
Ingest to Swift
Swift container: “ERA”
Swift path: <NOID>
The identifier in Swift will normally be the NOID generated in ERA. It may be some other identifier for non-ERA content (an identifier used in that project, or a UUID if nothing else is available). Swift X-Object-Meta name-value pairs will be populated:
project: normally “ERA” (this may become redundant if we always use a container per project, but we haven’t determined that yet)
Project_id: (i.e. the id of this object within the project) - normally the NOID
promise: a label for the level of preservation …
```

Make sure we are adding metadata to swift deposits as in AIP spec

---

lib/pushmi_pullyu/swift_depositer.rb

We have small bug in the current swift_depositor.rb code. When new swift object is created we use two API calls - one to create an object, another to write data to it. When archiving is turned on on the container, that cases file archive of 0 size been created when data in the file being updated. Fix is simple, just need to write file data in the create method.

Chage code to write file content during file creation

---

lib/pushmi_pullyu.rb
lib/pushmi_pullyu/version.rb

pushmipullyu gem was failing with the following error:
```ruby
/blah/gems/pushmi_pullyu-0.2.1/lib/pushmi_pullyu/logging.rb:4:in `<top (required)>': uninitialized constant PushmiPullyu (NameError)
```
This provides a fix for it. The issue was using the syntax `module PushmiPullyu::Logging` assumes the PushmiPullyu module has already been declared. Which it currently doesn't at this point. This can be fixed with either changing this syntax to use the longer version:
```
module PushmiPullyu
module Logging
```
Or a better solution is to move the version file to be the first thing that gets required (as it defines the PushmiPullyu module itself).
Already bumped the version number so we can release this right after this get's merged.

Fix loading issue with compact nested module syntax

---

.rubocop.yml

Here is a detailed summary, just for you ualberta-bot!

Rubocop warns about a renamed namespace that affects the config file.

---

lib/pushmi_pullyu/aip.rb
lib/pushmi_pullyu/version.rb

Overlooked the version change when first tagging the release. 
Updated the version number. Will tag a new release 1.0.1 with this change.

updated version number for new tagged release

---

lib/pushmi_pullyu/aip/file_list_creator.rb
lib/pushmi_pullyu/version.rb
pushmi_pullyu.gemspec

To allow the RDF gem to load the graph so that it can get the ordering of the files, it needs to authorize the access to list_source.

Add authentication to allow list source to be loaded

---

lib/pushmi_pullyu/cli.rb

I think this should resolve the issue Weiwei ran into this morning. I believe what's happening here is that when `PushmiPullyu.continue_polling?` is false, `wait_next_item` returns nil [here](https://github.com/ualbertalib/pushmi_pullyu/blob/master/lib/pushmi_pullyu/preservation_queue.rb#L62), feeding a [final nil item into the preservation cycle](https://github.com/ualbertalib/pushmi_pullyu/blob/master/lib/pushmi_pullyu/preservation_queue.rb#L62) prior to finally exiting. By returning immediately if the received item is nil, we jump directly to [exiting the preservation cycle](https://github.com/ualbertalib/pushmi_pullyu/blob/master/lib/pushmi_pullyu/cli.rb#L198).

Fix spurious error when stopping service

---

lib/pushmi_pullyu/aip/downloader.rb
lib/pushmi_pullyu/aip/fedora_fetcher.rb
lib/pushmi_pullyu/aip/file_list_creator.rb
lib/pushmi_pullyu/aip/owner_email_editor.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/preservation_queue.rb
lib/pushmi_pullyu/version.rb

We moved the DB connection setup to the console but the connection set up happens when the daemon was first started/restarted, and the connection will idle for a prolonged period of time and will be closed by the PostgreSQL DB. And when reading from DB is actually needed, the connection has often been killed by PG already. 
Move the db connection set up to where the connection is actually needed. This might be moved back to cli, once the PG DB we use is upgraded to the latest version, in which a connection timeout can be specified in the DB configuration.

have to move db connection back to where the connection is actually needed

---

.rubocop.yml
Dangerfile

Rubocop complains about using fail in Dangerfile and insists on using raise instead. However, danger uses fail with the sticky flag to specify how to treat the error. See https://danger.systems/reference.html
Have rubocop ignore Dangerfile

Fix danger error message

---

CHANGELOG.md
lib/pushmi_pullyu/version.rb
pushmi_pullyu.gemspec

Henry noticed when trying to take this to prod that it won't boot because we `require 'uuid'` for core functionality but accidentally declared it as a development dependency only rather than a runtime dep.
Change UUID to a runtime dependency, and bumped the version to 2.0.1 since we already pushed 2.0.0 to rubygems with the bad spec.

Fix dependency

---

CHANGELOG.md
examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
pushmi_pullyu.gemspec

This gem should be removed because a direct connection to a database is no longer needed. 
Related to #200 
Removed gem dependency

Remove pg dependency

---

.github/workflows/ruby.yml
CHANGELOG.md

> Starting March 1st, 2021 workflow runs that are triggered by Dependabot from push, pull_request, pull_request_review, or pull_request_review_comment events will be treated as if they were opened from a repository fork. This means they will receive a read-only GITHUB_TOKEN and will not have access to any secrets available in the repository.
Related to https://github.com/ualbertalib/jupiter/issues/2282
Changed Danger github action to use the read-only [GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) and the GithubActions bot.

Use read-only token for Danger

---

CHANGELOG.md
lib/pushmi_pullyu/version.rb

We want to release a new version which includes the json logging so that we can upgrade the version of Ruby.
Bumping version and changelog to 2.0.3

Bump CHANGELOG and VERSION for 2.0.3 release

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

We need cut a release that makes pushmi_pullyu more robust when a deposit fails in part of the workflow.
Bump version and CHANGELOG to 2.0.4

Bump CHANGELOG and VERSION for 2.0.4 release

---

CHANGELOG.md
lib/pushmi_pullyu/cli.rb

We are getting errors on the preservation cycle while waiting for the
next item in the redis queue. This small change will make sure we log
the problem so we can track it.

Add exception handling to preservation cycle

---

CHANGELOG.md
lib/pushmi_pullyu/aip/downloader.rb
spec/pushmi_pullyu/aip/downloader_spec.rb
spec/support/http_cache/vcr/aip_downloader_collection_run.yml
spec/support/http_cache/vcr/aip_downloader_community_run.yml
spec/support/http_cache/vcr/aip_downloader_run.yml

Collection and community models were not being fetched for AIP creation and were not saved for preservation. The latest changes on jupiter will open up community and collection information. This change makes PMPY aware of this and will handle AIP creation.
Related to #255 
Added logic to handle the creation of community and collection AIPs. These AIPs are very similar to the ones created for items and theses, with the exception that they will never include files.

Wip add community and collection to aips

---

CHANGELOG.md
README.md
examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/preservation_queue.rb
spec/fixtures/config.yml
spec/integration/acceptance_spec.rb
spec/pushmi_pullyu/cli_spec.rb
spec/pushmi_pullyu/preservation_queue_spec.rb

When an entity fails to be deposited, PMPY would only wait for the minimum age to retry to ingest the entity. This creates the problem where we don't let the problem be fixed and we flood the logs with information that is no longer useful.
This change doubles the time of each attempt to give space for the problems to be fixed. There are 3 configuration parameters added:
- **ingestion_prefix**: The prefix used for Redis keys storing the failed attempt count - Default value of  - Default value of `prod:pmpy_ingest_attempt:`
- **ingestion_attempts**: The max number of re-ingestion attempts - Default value of `15`
- **first_failed_wait**: The time to add at the beginning which will be double every retry - Default value of `10`
The default values will keep retrying for around a week and drop …

Add delay on entity re-ingestion on failed attempt

---

CHANGELOG.md
lib/pushmi_pullyu/aip/downloader.rb
lib/pushmi_pullyu/cli.rb

Please describe any relevant motivation and context for these changes.
PMPY was not working in staging and all preservation attempts failed. PMPY could not find the full path to jupiter because it was using the URI request_uri which is the path after the localhost. If PMPY and jupiter are on different servers, this will not work.
Related to #297
Changed use of method URI.request_uri to joining URI with new path.

Solve communication problems with jupiter

---

CHANGELOG.md
lib/pushmi_pullyu/cli.rb

We had recurring nil exceptions being logged. This was due to a basic error in the code scope.
Related to #314 
Moved log method to the correct scope.

Make sure the exception is in the scope

---

CHANGELOG.md
examples/pushmi_pullyu.yml
lib/pushmi_pullyu.rb
lib/pushmi_pullyu/cli.rb
lib/pushmi_pullyu/swift_depositer.rb
spec/fixtures/config.yml
spec/pushmi_pullyu/swift_depositer_spec.rb
spec/support/http_cache/vcr/swift_auth_v3.yml

This PR adds configuration options to create Swift depositer objects configured with V3 authentication.
This configuration will be used with the move to OLRC.
We are moving Swift destination from local to OLRC. This requires a different type of authentication. The rest of the behaviour stays the same.
Related to #349
Adds configuration options and tests for authenticating on Openstack Swift servers with V3 authentication.

Add support for V3 authentication for Swift

---

CHANGELOG.md
docker-compose.yml
lib/pushmi_pullyu/swift_depositer.rb
spec/pushmi_pullyu/swift_depositer_spec.rb

We've been having multiple authentication token errors due to invalidation. This PR Fixes this
Related to #315 
- Set a parameter default value that makes the ruby-openstack gem retry to refresh the auth token.
- Add an http header to refresh the token on each call.
- Catch the exception when a token is invalid and recreate the connection.

Fix problem with authentication token expiration

---

CHANGELOG.md
lib/pushmi_pullyu/aip/creator.rb
lib/pushmi_pullyu/swift_depositer.rb

@beausapach asked "Is there a process that's holding the file open?  The space may not be freed until it's closed, which would happen at shutdown."
With no associated block, `File.open` is a synonym for `File.new`.  The `new` method returns a `File` instance that you can then read or write from. The file remains open until `close` is called on the instance. Once the file variable goes out of scope, then garbage collection will eventually close it, but this may not happen for a while. Meanwhile, resources are being held open.  (From [Ruby 3.3: Opening and Closing Files](https://learning.oreilly.com/library/view/programming-ruby-3-3/9798888650684/f_0082.xhtml#d25e38151))
Related to #475 
Use File.open with a block for simple exception handling and ensuring files are closed

Use File.open with a block for simple exception handling and ensuring files are closed

---

.github/workflows/ruby.yml
Dangerfile
README.md

CI stopped working when the branch name was renamed from master to main.
Update CI and some documentation with main branch.

Update CI for branch name changes

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

Prepare for 2.1.4 release
Updated CHANGELOG and version.rb version.

Bump CHANGELOG and VERSION for 2.1.4 release

---

CHANGELOG.md
Gemfile.lock
pushmi_pullyu.gemspec

We've had troubles deploying 2.1.4 in staging.  We observed it installing newer versions of gems versus what was in our Gemfile.lock that don't work in Ruby 2.7.
Adjust pushmi_pullyu.gemspec to avoid gems that only work in Ruby 3+ environments.

Permit versions of activesupport that work with Ruby 2.7

---

CHANGELOG.md
Gemfile.lock
lib/pushmi_pullyu/version.rb

Prepare for version 2.1.5 release and update changelog.
Update version.rb and CHANGELOG.md

Bump version 2.1.5

---

CHANGELOG.md
Gemfile.lock
pushmi_pullyu.gemspec

Staging is blocked by deployment issue. Recent minor releases of gem dependencies have move to require Ruby 3.x because 2.7 is eol. We pin major versions in pushmi_pullyu.gemspec
Related to #492 
Pin securerandom to 0.3.2 (0.4.0 depends on Ruby 3)

Pin version of securerandom that work with Ruby 2.7
